### ISSUE TITLE
特定の名前のラベルが定義できない

### ISSUE THREAD

**Issue by SuperTurboZ** [AILight/AILZ80ASM#172]
行頭で C8025H: というラベルを定義するとエラーになってしまうようです。
頭にアンダースコアを入れて _C8025H: とするとエラーは出ませんでした。
PE というラベル名もエラーになりました。
```
;AILZ80ASM test code
;特定の名称のラベルが定義できない
	org	0
C8025H:
PE:
	nop
```

**Comment by fuzz6001** [comment]
@SuperTurboZ 
v1.0.1.0で確認してみたところ、
> E0013: ラベルの指定が間違っています。記号や予約語や数値に変換できる文字列は使えません。

というエラーが出ました。
`C8025H`は数値（16進数）、`PE`は予約語なので、エラーが出るのは仕様だと思います。

**Comment by AILight** [comment]
みなさん、ご指摘ありがとうございました。とても良いご指摘を頂きました。こちらのアセンブラは、ラベルに利用できる文字の記述を忘れていましたので、以下の通り追加させていただきました。
次のリリースで、ドキュメントも修正されます。ありがとうございました。大変助かりました。

---------------------------------------------------------------
#### ラベルに使用できる文字と出来ない文字列
- ラベルに使用できる文字
  - 英文字: a-zA-Z
  - 数字: 0-9
  - 記号: -
- ラベルに使用できない文字列
  - 先頭が数字の文字列
  - 数値に変換できる文字列
  - 予約文字列（命令名、レジスタ名、フラグ名）

#### 大文字と小文字の区別
- 大文字と小文字は区別しません

**Comment by SuperTurboZ** [comment]
本来、コーディング時に予約語のラベル使用は避けておくべき事ですね。
AILZ80ASMに限らず、古いソースを別のアセンブラに通してみると思わぬところでエラーが出ます。
アセンブラの仕様や制限について改めて考えてみる良い機会になりました。

**Comment by AILight** [comment]
正直言うと、フラグ名はラベルに使っても問題ないかな？（未評価）とは思っていますが、人間が判別するという意味では、面倒にもなりそうですので今回はまとめて予約語とさせていただきました。

以下のバージョンで修正が行われました。
- [AILZ80ASM v1.0.3](https://github.com/AILight/AILZ80ASM/releases/tag/v1.0.3)
