### ISSUE TITLE
How can I use your assembler for my .NET project without invoking the .exe?

### ISSUE THREAD

**Issue by SuperJMN** [AILight/AILZ80ASM#176]
I'd like to have something like this:

```charp
var assembler = new Z80Assembler();

var source = @"CALL main
HALT
main:
LD hl, 30h
LD (hl), 1
RET";

byte[] output = assembler.Assemble(source);
```

Is it doable with your library? Thanks!

Also, it would be great if you translated the usage to English, for a wider usage :)

**Comment by AILight** [comment]
Thank you for your question.

The current version does not have that feature. But the idea is good and I would like to implement it in the future.

**Comment by SuperJMN** [comment]
Thanks a lot for your quick response! I'm creating a compiler for the Z80 and this would be really useful.
I'm really looking forward to news on this :D
