### ISSUE TITLE
high/low演算子を大文字で指定するとエラーになる

### ISSUE THREAD

**Issue by SuperTurboZ** [AILight/AILZ80ASM#185]
readmeには演算子で大文字と小文字が区別されるのか分からなかったので仕様か不具合化はわかりませんが、high/low演算子を大文字でHIGH/LOWと書くとエラーになるようです。
普段は小文字で書くことが多いので気が付きませんでしたが、他の方のコードをアセンブルして気が付きました。
仕様であればreadmeに記載があった方がよいかもしれません。

**Comment by AILight** [comment]
ご指摘ありがとうございます。特に考えずに実装してしまっていましたので、他のアセンブラを確認しながら演算子の扱いを考えたいと思います。

**Comment by AILight** [comment]
大文字小文字の区別をしないように変更しました。ドキュメントにも追記させていただきました。ご指摘ありがとうございました。

以下のバージョンで修正が行われました。
- [AILZ80ASM v1.0.3](https://github.com/AILight/AILZ80ASM/releases/tag/v1.0.3)
