### ISSUE TITLE
マクロの引数で指定したレジスタ名が第一オペランドへ適用できない

### ISSUE THREAD

**Issue by SuperTurboZ** [AILight/AILZ80ASM#187]
下記のようなマクロ参照で２つのエラーが出ました。
これらは仕様による制限になるのでしょうか。

１．マクロの[引数]にレジスタ名'C'を指定しても、ld [引数],h でエラーになる
　マクロの引数でソースオペランドにレジスタ名を引き渡せないようです。

２．マクロ内に REPT-ENDM ブロックを含めるとエラーになる。
　マクロの仕様にはネスト可能と記載がないので仕様上の制約でしょうか。
　最後の endm を削除するとエラーは出なくなりますが、REPT-ENDM間のコードは生成されないようです。
```
;(u24)AHL = (u8)A * (u16)DE , ZERO_REG = 0
 umul0816_ahl_a_de	macro ZERO_REG
	ld	hl,0
	ld	ZERO_REG,h	;<-- 無効な命令が指定されました。   
;	ld	h,ZERO_REG	;<-- こちらは通りました
	add	a,a		;CF=XL[7]
	jr	nc,$+2+2	;bit7
	ld	l,e		;+Y
	ld	h,d
;30 : 33
  REPT 7	;bit6..0
	add	hl,hl
	adc	a,a		
	jr	nc,$+2+2
	add	hl,de		;+Y
	adc	a,ZERO_REG	;+CY
  ENDM
;27 : 37 x7
 endm				;<--  END MACRO (ENDM) が先に見つかりました。

	umul0816_ahl_a_de C  ; ZERO_REG に Cレジスタを指定 
```

**Comment by AILight** [comment]
良いご指摘を頂きありがとうございます。こちらの機能を作る準備はされていたので、実装はそれほど難しくなく完了しました。次のバージョンでアセンブル可能となります。

**Comment by SuperTurboZ** [comment]
よろしくおねがいします。
マクロ内の REPT-ENDMについてはversion 1.0.3.0でコードの展開ができているようでした。

**Comment by AILight** [comment]
以下のバージョンで修正が行われました。
- [AILZ80ASM v1.0.4](https://github.com/AILight/AILZ80ASM/releases/tag/v1.0.4)
