### ISSUE TITLE
DSが期待通りに動かない場合がある

### ISSUE THREAD

**Issue by tablacus** [AILight/AILZ80ASM#274]
いつも便利に使わせてもらっています。
AILZ80ASM version 1.0.12.0でDSが期待通りにならなくなっている場合があったので報告します。

ソースは https://github.com/tablacus/LSX-Dodgers のPC-8801mkIISR版になります。
`ASM_AILS80ASM_88.BAT`でアセンブルしています。

こちらの画像は該当部分で左がAILZ80ASM version 1.0.0.0で右がAILZ80ASM version 1.0.12.0です。
![image](https://github.com/AILight/AILZ80ASM/assets/5156977/6d384290-62f0-4b7c-b5a2-ee8361cde9c1)
この`DS  INTAD-AT_TABLE`の部分の`DS`が右側で期待通りになっていない部分です。
`INITAD`は`0EE00H`で`AT_TABLE`は`0EDE3H`なので一番左のカウンタが増えると期待しているのですが右側では`001FEA`のままです。

X1/turbo/Z版 と MZ-700/1500版 ではほぼ同じ要領で`DS`を使っているのですが期待通りに動作しています。
そういう訳でPC-8801mkIISR版だけこちらのバグでこうなっているのかも知れません。
すみませんが、調べていただけると嬉しいです。

**Comment by AILight** [comment]
ご迷惑をおかけしております。申し訳ございません。
DSの出力に関してはちょっと変更があったかと思います。確認をさせていただきます。

**Comment by AILight** [comment]
こちらでも環境を作らせていただいて確認をしました。
これからテストコードを書いてテストを行っていきます。
![image](https://github.com/AILight/AILZ80ASM/assets/17267565/9cb75d5b-9b84-418a-8562-a408369f8a14)

**Comment by tablacus** [comment]
回避策を発見しました。
`SUB.ASM`のORG指定を[前回](https://github.com/AILight/AILZ80ASM/issues/262)のORGの第2引数と同じ対応にしたところ正常にアセンブルできるようになりました。

```SUB.ASM
	ORG	$$+OFFSET,$$	;$DEPHASE
```
SUB.ASMの最後の方です。
![image](https://github.com/AILight/AILZ80ASM/assets/5156977/bf818efa-4de9-4ba6-a13c-54aab3096c56)

**Comment by tablacus** [comment]
アドレスを揃えるのに`ALIGN`が便利そうなので使ってみたのですが`88INTVEC.ASM`で`ALIGN`の後の`DS`が期待通りには動作しませんでした。
こちらも同じ個所が原因のような気がします。

旧
```88INTVEC.ASM
AT_TABLE:
	DS	INTAD-AT_TABLE
```
![image](https://github.com/AILight/AILZ80ASM/assets/5156977/c8d9dc6f-d5d8-4961-92d7-1e7991c8cdec)

新
```88INTVEC.ASM
	ALIGN	256
```


![image](https://github.com/AILight/AILZ80ASM/assets/5156977/ab9871e1-441b-41c2-96cc-570676b2f5e9)

**Comment by AILight** [comment]
ありがとうございます。現象の確認はできているのですが、テスト用に使うコードをうまく作れなくて困っていました。調査していただいた結果を参考にさせていただきながら引き続き調査を行いたいと思います。

**Comment by AILight** [comment]
おかげさまで上手くテストコードが書けました。引き続き調査を行います。
![image](https://github.com/AILight/AILZ80ASM/assets/17267565/f4d92c07-db08-4871-9e9d-9b296083725d)

**Comment by AILight** [comment]
プログラムの修正が完了しました。年内にリリース予定です。

**Comment by AILight** [comment]
修正版をリリースしました。

**Comment by tablacus** [comment]
ALIGNも正常に動作することを確認しました。
ますます便利に使えます。
対応ありがとうございました。

**Comment by AILight** [comment]
ご確認ありがとうございます。バグレポートをいただきまして大変助かりました。
今後AILZ80ASMに大きな修正が入るときには、LSX-Dodgersのアセンブル結果が一致しているか確認させていただきます。現在は手動確認ですので漏れが発生する可能性があるのですが、時間が出来ましたらリリース時に自動でチェックできるようにしたいと思っております。

**Comment by tablacus** [comment]
AILZ80ASMはORGの第2引数を用いることで入り組んだコードをすっきりとしたLSTに出力できるので非常に助かっております。
また、OFFSETを活用できればますます便利に使える予感がします。
