### ISSUE TITLE
db を使ったときのアセンブル速度について

### ISSUE THREAD

**Issue by ueno1969** [AILight/AILZ80ASM#332]
ちょっと気になりましたので報告いたします。

アセンブル速度についてですが、
>  ld a, $00

の場合と

>  db $00, $00

の場合で大幅に速度が異なります。

アバウトで申し訳ないのですが、これらを4000行並べたファイルをアセンブルすると、前者だと0.5s程度で終わるのですが後者だと2sほどかかります。
処理の仕方が異なるので差がでるとは思いますが、こんなに差が出るものでしょうか？

8000行でも試しましたがこんな感じになりました。

```
| 行数 | ld   | db   |
| 4000 | 0.5s | 2s   |
| 8000 | 0.6s | 2.9s | 
```

- 環境
  - CPU: i5-13400
  - OS: Windows 11

- 参考
  -  [ファイルの置き場所(gist)](https://gist.github.com/ueno1969/f9b1650fc2c235d1764992d5e59553b7)

**Comment by AILight** [comment]
ご報告ありがとうございます。確かに何か悪さをしている処理があるかもしれませんので、後で確認をしたいと思います。

**Comment by AILight** [comment]
こちら、DBは文字列やFunctionのパースをする必要があるのですが、その中で「,」の切り出しが難しい処理となります。その処理を動かすために処理内容的に重めの処理を動かす必要があり、遅くなっていると思われます。

```
DB "ABC,DEF". $12, FUNC(1, 2)
```

**Comment by ueno1969** [comment]
正解ではないかもしれませんが、こちらでは速度アップしましたので一応プルリクエストを送らせていただきました。

**Comment by AILight** [comment]
プルリクエストの作成ありがとうございます。こちらの空き時間あまりとれなく、8/10以降の作業にさせてください。遅くなり申し訳ございません。

**Comment by ueno1969** [comment]
今はこちらでForkしてビルドしたものを使って試してみています。
特に対応が遅くなっても全く問題ありませんのでお好きなタイミングでお願いします。

**Comment by AILight** [comment]
リリースしました。PRありがとうございました。

**Comment by ueno1969** [comment]
リリースありがとうございます。
自作プログラムで、前バージョンと-dfで比較しても同一結果が得られました。
