### ISSUE TITLE
DBのループの変数名で "|"が許容される

### ISSUE THREAD

**Issue by ueno1969** [AILight/AILZ80ASM#334]
DBのループの変数名で "|"が許容されています。
そのため、"X|Y"のような変数が利用できます。
通常そんなことしないとは思いますが、おそらく意図とは違う動作かと思いますので一応報告させていただきます。

```
;*** AILZ80ASM *** Z-80 Assembler, version 1.0.21.0, LST:Full:4
                                
000000 0000 000102                  DB [X|Y=0..2:X|Y]
[EOF:sample.asm:UTF_8]
```

おそらく [OperationItemData](https://github.com/AILight/AILZ80ASM/blob/main/AILZ80ASM/OperationItems/OperationItemData.cs#L35)の正規表現が `[a-z|A-Z|0-9|_]` でなく、` [a-zA-Z0-9_]` となるかと思います。

**Comment by AILight** [comment]
ご指摘ありがとうございます。

**Comment by AILight** [comment]
修正を行ったPRを作成させていただきました。ご確認をいただけますでしょうか？
https://github.com/AILight/AILZ80ASM/pull/339

**Comment by AILight** [comment]
コンフリクト対応を行いましたので、マージさせていただきます。

**Comment by AILight** [comment]
リリースしました。
