### ISSUE TITLE
ローカルラベルを使った場合のSymbolファイルの値がおかしい

### ISSUE THREAD

**Issue by ueno1969** [AILight/AILZ80ASM#81]
ローカルラベルを使った場合のSymbolファイルについてです。

下の例をご参照ください。
デフォルトのネームスペース```NS_Main```がついている場合には、NS_Main.label1と NS_Main.label1.l2が正しいアドレスを指していますが、ネームスペースが省略されている場合では、 label1.l2がなく、label1が2度書かれています。
```C002 label1.l2```となるのが正しいのかと思いますがどうでしょうか？

## 例

バージョン: v0.9.9.1 ベータリリース9.1

> AILZ80ASM.exe sample.asm --symbol --list

- sample.asm

  ~~~
      org $c000;
  
  label1:
      ld a,1
  .l2
      ld b,1
  ~~~

- sample.sym

  ~~~
  C000 label1
  C002 label1
  C000 NS_Main.label1
  C002 NS_Main.label1.l2
  ~~~

- sample.lst

  ~~~
                                  *** AILZ80ASM *** Z-80 Assembler, version 0.9.9.1
  000000 C000                         org $c000;
                                  
                                  label1:
  000000 C000 3E01             7      ld a,1
                                  .l2
  000002 C002 0601             7      ld b,1
  [EOF:sample.asm:UTF_8]
  ~~~

**Comment by AILight** [comment]
不具合として確認ができました。ご報告ありがとうございます。次のリリースでは、以下のようになります。内容をみていただいて問題なければこのままリリースになるかと思います。コマンドライン引数がちょっと変更になりましたので、ご注意ください。

バージョン: v0.9.9.4 ベータリリース9.4
> AILZ80ASM.exe .\sample.asm -lst -sym

- sample.asm
```
    org $c000;

label1:
    ld a,1
.l2
    ld b,1
```

- sample.sym
```
*** AILZ80ASM *** Z-80 Assembler, version 0.9.9.4, SYM
C000 label1
C002 label1.l2
```

- sample.lst
```
                                *** AILZ80ASM *** Z-80 Assembler, version 0.9.9.4, LST:Full:4
000000 C000                         org $c000;
                                
                                label1:
000000 C000 3E01             7      ld a,1
                                .l2
000002 C002 0601             7      ld b,1
[EOF:sample.asm:UTF_8]
```

**Comment by AILight** [comment]
ベータリリース9.4を発行させていただきました。
https://github.com/AILight/AILZ80ASM/releases/tag/v0.9.9.4

**Comment by ueno1969** [comment]
確認遅くなりました。
最新版の 0.9.9.7の出力で正しくなっていました。
これでデバッグがはかどります。
どうもありがとうございました。
